export const LAYOUT_CONFIG = {
  INITIAL_CONTENT_RATIO: 0.666,
  
  MIN_CONTENT_RATIO: 0.18,
  
  MAX_CONTENT_RATIO: 0.666,
  
  MARGIN: 10,
  
  SNAP_THRESHOLD_LOW: 0.25,
  
  SNAP_THRESHOLD_MID: 0.5,
  
  SNAP_THRESHOLD_HIGH: 0.75,
  
  SCROLL_HEIGHT_RATIO: 3,
  
  SCROLL_LOCK_DURATION: 200
}