export const LAYOUT_CONFIG = {
  INITIAL_CONTENT_RATIO: 0.55,
  
  MIN_CONTENT_RATIO: 0.18,
  
  // 首页始终保留至少四分之一地图语境。
  MAX_CONTENT_RATIO: 0.70,
  
  MARGIN: 10,
  
  SNAP_THRESHOLD_LOW: 0.25,
  
  SNAP_THRESHOLD_MID: 0.5,
  
  SNAP_THRESHOLD_HIGH: 0.75,
  
  SCROLL_HEIGHT_RATIO: 3,
  
  SCROLL_LOCK_DURATION: 180,

  DRAG_THRESHOLD: 8,

  FLING_VELOCITY: 0.45
}
